-- MySQL Script generated by MySQL Workbench
-- Fri Nov  1 22:58:34 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema codeforgoodteam9
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema codeforgoodteam9
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `codeforgoodteam9` DEFAULT CHARACTER SET utf8mb4 ;
USE `codeforgoodteam9` ;

-- -----------------------------------------------------
-- Table `codeforgoodteam9`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codeforgoodteam9`.`users` (
  `user_id` INT(11) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `country_of_residence` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `country_of_residence_idx` (`country_of_residence` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `codeforgoodteam9`.`universities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codeforgoodteam9`.`universities` (
  `university_id` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`university_id`),
  INDEX `country_idx` (`country` ASC) VISIBLE,
  CONSTRAINT `country`
    FOREIGN KEY (`country`)
    REFERENCES `codeforgoodteam9`.`users` (`country_of_residence`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = '		';

USE `codeforgoodteam9` ;

-- -----------------------------------------------------
-- procedure add_university
-- -----------------------------------------------------

DELIMITER $$
USE `codeforgoodteam9`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `add_university`(in University_id int(11), Name varchar(45), Country varchar(45))
BEGIN
	insert into codeforgoodteam9.universities(university_id, name, country)
		values(University_id, Name, Country);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure add_user
-- -----------------------------------------------------

DELIMITER $$
USE `codeforgoodteam9`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `add_user`(in User_id int(11), First_name varchar(45), Last_name varchar(45), Country_of_residence varchar(45))
BEGIN
	insert into codeforgoodteam9.users(user_id, first_name, last_name, country_of_residence)
		values(User_id, First_name, Last_name, Country_of_residence);
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
